name: cancer-surgery-nlp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - nltk
  - spacy
  - pip
  - spacy
  - pip:
      - transformers
      - torch
      - https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.4/en_core_sci_sm-0.5.4.tar.gz
